TEMPLATE = subdirs
CONFIG += ordered

include (browserui.pri)

SUBDIRS += bedrockProvisioning
SUBDIRS += browsercore
SUBDIRS += ginebra2
# rom MUST come last because it depends on *_template.pkg files generated by qmake from all the other apps
SUBDIRS += rom

symbian: { 

contains(what, plat_101 ) {
    BLD_INF_RULES.prj_exports += "$${LITERAL_HASH}include <platform_paths.hrh>" \
                                 "rom/browser.iby  CORE_APP_LAYER_IBY_EXPORT_PATH(browser.iby)"
    }  
}
